export enum CityName{
    // 'yunlinCounty'='雲林縣',
    // 'nantouCountry'='南投縣',
    // 'lianjiangCountry'='連江縣',
    // 'taitungCountry'='台東縣',
    // 'kinmenCountry'='金門縣',
    // 'yilan'='',
    // 'pintung'='',
    // 'miaoli'='',
    // ''='',
    // ''='',
    // ''='',
    // ''='',
    // ''='',
    // ''='',
    // ''='',
    // ''='',
    // ''='',
    // ''='',
    // ''='',
    // ''='',
    // ''='',    
}
